fix ChangeVision/astah-emf#9022 ASY用プラグインが使用するarchetypeを用意する
ChangeVision/safety-plugin-archetype-plugin pull request #1
Opened 2020-09-03 07:11 UTC by yoichi-nakaya

ChangeVision/astah-emf#9022

2020-09-06 23:29 UTC, aasakawa requested changes

2020-09-06 23:29 UTC, aasakawa commented on src/main/resources/archetype-resources/pom.xml
> +			<url>http://download.java.net/maven/2</url>
@yoichi-nakaya @kamura このリポジトリは既に停止されています。
何の目的で設定されているのかわかりませんが、削除した方が良さそうに思います。

2020-09-06 23:29 UTC, aasakawa commented on src/main/resources/archetype-resources/pom.xml
> +			<url>http://uk.maven.org/maven2/</url>
@yoichi-nakaya こちらも既に停止されています。

昔は本家の中央リポジトリが遅かったり、不安定だったりで、他を指定していることがあったような？
個別にミラーを指定したり、今は適切にロードバランスされていて困ることは無くなっているので削除で良いかと。

2020-09-06 23:29 UTC, aasakawa commented on src/main/resources/archetype-resources/pom.xml
> +				<version>2.1.2</version>
@yoichi-nakaya @kamura 全体的にプラグインのバージョンが 10 年単位で古いですね。
これから新規に作るモジュールのひな型がここまで古いと、人よってはドン引きしそうに思います。

2020-09-06 23:29 UTC, aasakawa commented on src/main/resources/archetype-resources/pom.xml
> +		</testResources>
@yoichi-nakaya `<build>` 内はここまでデフォルトそのままですが、指定する意味あるのでしょうか。

2020-09-06 23:29 UTC, aasakawa commented on src/main/resources/archetype-resources/pom.xml
> +						<link>http://java.sun.com/javase/ja/6/docs/ja/api/</link>
@yoichi-nakaya Java6 はさすがにまずいと思います。

2020-09-06 23:29 UTC, aasakawa commented on src/main/resources/archetype-resources/pom.xml
> +					<outputEncoding>UTF-8</outputEncoding>
@yoichi-nakaya [java - How to configure encoding in Maven? - Stack Overflow](https://stackoverflow.com/questions/3017695/how-to-configure-encoding-in-maven) にあるように、かなり前から共通のプロパティを指定するだけで個別に指定する必要は無くなりました。

`astah-emf/pom.xml` では STAMP W/B 辺りのタイミングで調整済みなので、そちらを参考にしてみて下さい。

```xml
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
</properties>
```

2020-09-06 23:29 UTC, aasakawa commented on src/main/resources/archetype-resources/pom.xml
> +					<target>1.8</target>
@yoichi-nakaya [Apache Maven Compiler Plugin – Setting the -source and -target of the Java Compiler](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html) でもどちらでも良いように書かれていますが、共通で定義しておけば、 `maven-javadoc-plugin` でもその値を再利用できます。



```xml
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```

2020-09-07 07:21 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +			<url>http://download.java.net/maven/2</url>
@aasakawa 削除しました

2020-09-07 07:22 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +			<url>http://uk.maven.org/maven2/</url>
@aasakawa 削除しました

2020-09-07 07:22 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +				<version>2.1.2</version>
@aasakawa バージョンを最新にしました

2020-09-07 07:22 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +		</testResources>
@aasakawa 削除しました

2020-09-07 07:22 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +						<link>http://java.sun.com/javase/ja/6/docs/ja/api/</link>
@aasakawa Java8に修正しました

2020-09-07 07:22 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +					<outputEncoding>UTF-8</outputEncoding>
@aasakawa 共通のプロパティを指定しました

2020-09-07 07:22 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +					<target>1.8</target>
@aasakawa 共通で定義しました

2020-09-07 08:24 UTC, aasakawa requested changes

2020-09-07 09:36 UTC, yoichi-nakaya commented on src/main/resources/archetype-resources/pom.xml
> +				<version>3.9.1</version>
@aasakawa 上記のように修正しました

2020-09-08 04:35 UTC, aasakawa approved these changes

2020-09-08 04:35 UTC, merged